C:/VulkanSDK/1.4.321.1/Bin/glslc.exe shader.vert -o vert.spv
C:/VulkanSDK/1.4.321.1/Bin/glslc.exe shader.frag -o frag.spv
C:/VulkanSDK/1.4.321.1/Bin/glslc.exe phong.vert -o phong_vert.spv
C:/VulkanSDK/1.4.321.1/Bin/glslc.exe phong.frag -o phong_frag.spv
C:/VulkanSDK/1.4.321.1/Bin/glslc.exe shadow.vert -o shadow_vert.spv
C:/VulkanSDK/1.4.321.1/Bin/glslc.exe shadow.frag -o shadow_frag.spv
C:/VulkanSDK/1.4.321.1/Bin/glslc.exe water.vert -o water_vert.spv
C:/VulkanSDK/1.4.321.1/Bin/glslc.exe water.frag -o water_frag.spv
C:/VulkanSDK/1.4.321.1/Bin/glslc.exe checkerboard.vert -o checkerboard_vert.spv
C:/VulkanSDK/1.4.321.1/Bin/glslc.exe checkerboard.frag -o checkerboard_frag.spv
C:/VulkanSDK/1.4.321.1/Bin/glslc.exe collider_wire.vert -o collider_wire_vert.spv
C:/VulkanSDK/1.4.321.1/Bin/glslc.exe collider_wire.frag -o collider_wire_frag.spv
C:/VulkanSDK/1.4.321.1/Bin/glslc.exe flatcolor.vert -o flatcolor_vert.spv
C:/VulkanSDK/1.4.321.1/Bin/glslc.exe flatcolor.frag -o flatcolor_frag.spv
C:/VulkanSDK/1.4.321.1/Bin/glslc.exe gouraud.vert -o gouraud_vert.spv
C:/VulkanSDK/1.4.321.1/Bin/glslc.exe gouraud.frag -o gouraud_frag.spv
C:/VulkanSDK/1.4.321.1/Bin/glslc.exe sand.frag -o sand_frag.spv
C:/VulkanSDK/1.4.321.1/Bin/glslc.exe base.frag -o base_frag.spv
C:/VulkanSDK/1.4.321.1/Bin/glslc.exe glass.frag -o glass_frag.spv
C:/VulkanSDK/1.4.321.1/Bin/glslc.exe transparent.frag -o transparent_frag.spv
C:/VulkanSDK/1.4.321.1/Bin/glslc.exe skybox.vert -o skybox_vert.spv
C:/VulkanSDK/1.4.321.1/Bin/glslc.exe skybox.frag -o skybox_frag.spv
C:/VulkanSDK/1.4.321.1/Bin/glslc.exe post.vert -o post_vert.spv
C:/VulkanSDK/1.4.321.1/Bin/glslc.exe post.frag -o post_frag.spv
C:/VulkanSDK/1.4.321.1/Bin/glslc.exe snow.vert -o snow_vert.spv
C:/VulkanSDK/1.4.321.1/Bin/glslc.exe snow.frag -o snow_frag.spv
C:/VulkanSDK/1.4.321.1/Bin/glslc.exe snow.comp -o snow_comp.spv
C:/VulkanSDK/1.4.321.1/Bin/glslc.exe rain.vert -o rain_vert.spv
C:/VulkanSDK/1.4.321.1/Bin/glslc.exe rain.frag -o rain_frag.spv
C:/VulkanSDK/1.4.321.1/Bin/glslc.exe rain.comp -o rain_comp.spv
C:/VulkanSDK/1.4.321.1/Bin/glslc.exe fire.vert -o fire_vert.spv
C:/VulkanSDK/1.4.321.1/Bin/glslc.exe fire.frag -o fire_frag.spv
C:/VulkanSDK/1.4.321.1/Bin/glslc.exe fire.comp -o fire_comp.spv
C:/VulkanSDK/1.4.321.1/Bin/glslc.exe dust.vert -o dust_vert.spv
C:/VulkanSDK/1.4.321.1/Bin/glslc.exe dust.frag -o dust_frag.spv
C:/VulkanSDK/1.4.321.1/Bin/glslc.exe dust.comp -o dust_comp.spv
C:/VulkanSDK/1.4.321.1/Bin/glslc.exe smoke.vert -o smoke_vert.spv
C:/VulkanSDK/1.4.321.1/Bin/glslc.exe smoke.frag -o smoke_frag.spv
C:/VulkanSDK/1.4.321.1/Bin/glslc.exe smoke.comp -o smoke_comp.spv
C:/VulkanSDK/1.4.321.1/Bin/glslc.exe particle.vert -o particle_vert.spv
C:/VulkanSDK/1.4.321.1/Bin/glslc.exe particle.frag -o particle_frag.spv
C:/VulkanSDK/1.4.321.1/Bin/glslc.exe particle.comp -o particle_comp.spv
pause
